# Generated by Django 3.2.14 on 2022-08-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=10)),
                ('turmas', models.CharField(max_length=150, null=True)),
                ('salas', models.CharField(max_length=100, null=True)),
                ('professores', models.CharField(max_length=100, null=True)),
                ('cargas', models.CharField(max_length=30, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_Employee',
        ),
    ]
